In [2]:
import pandas as pd
import os

# Посмотрим что внутри одного файла
df = pd.read_excel("../data/raw/nbk_2023_capital_assets.xls", header=None)
print(df.shape)
df.head(20)

(41, 28)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Two tier banks' Financial indicators1 on Janua...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,№,Name of two tier bank,Assets,Total loans2,NaN,"of these, loans with overdue payments3",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,in all,including,over 7 days,NaN,over 30 days,NaN,over 90 days,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,Reverse REPO operations,amount,share in loan portfolio,amount,share in loan portfolio,amount,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,"""Halyk Bank of Kazakhstan"", JSC",13862789955,8087487621,5000179,232144910,0.0287,201713157,0.0249,145119929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2,"""Kaspi Bank"", JSC",5086784318,3380024868,10006311,250842651,0.0742,215786208,0.0638,175112856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3,"""Bank CenterCredit"", JSC",4346622613,2161666091,73144699,84783223,0.0392,68082896,0.0315,56890749,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,4,"""Otbasy bank"", JSC",3440104965,2984577792,16263119,25119479,0.0084,11900021,0.004,2064949,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,5,"""ForteBank"", JSC",2914126826,1275636947,45125454,73405960,0.0575,66199596,0.0519,56994750,...,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
13,6,"""First Heartland Jusan Bank"", JSC",2843661507,1139776680,350370,150184860,0.1318,141654477,0.1243,130789142,...,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
14,7,"""Eurasian Bank"", JSC",2360045578,1152973628,NaN,105244884,0.0913,83089571,0.0721,65646077,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,8,"""Bank RBK"" Bank"", JSC",1984418179,945226623,18244716,33899461,0.0359,31281385,0.0331,29465548,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
16,9,"""Bereke Bank"", JSC",1694922688,1324575404,NaN,136092346,0.1027,117624740,0.0888,107020752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,10,"""Citibank Kazakhstan"", JSC",1334705356,124626523,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,11,"""Bank Freedom Finance Kazakhstan"", JSC",1264198200,343481254,41559520,2556764,0.0074,285886,0.0008,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,12,"""Altyn Bank"", JSC (SB of China Citic Bank Corp...",981451106,337306001,10034339,4165542,0.0123,3011224,0.0089,2119449,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Посмотрим строки с 5 по 15
df.iloc[5:20, 0:5]

,0,1,2,3,4
5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,in all,including
7,NaN,NaN,NaN,NaN,Reverse REPO operations
8,1,"""Halyk Bank of Kazakhstan"", JSC",13862789955,8087487621,5000179
9,2,"""Kaspi Bank"", JSC",5086784318,3380024868,10006311
10,3,"""Bank CenterCredit"", JSC",4346622613,2161666091,73144699
11,4,"""Otbasy bank"", JSC",3440104965,2984577792,16263119
12,5,"""ForteBank"", JSC",2914126826,1275636947,45125454
13,6,"""First Heartland Jusan Bank"", JSC",2843661507,1139776680,350370
14,7,"""Eurasian Bank"", JSC",2360045578,1152973628,NaN
15,8,"""Bank RBK"" Bank"", JSC",1984418179,945226623,18244716
16,9,"""Bereke Bank"", JSC",1694922688,1324575404,NaN
17,10,"""Citibank Kazakhstan"", JSC",1334705356,124626523,NaN
18,11,"""Bank Freedom Finance Kazakhstan"", JSC",1264198200,343481254,41559520
19,12,"""Altyn Bank"", JSC (SB of China Citic Bank Corp...",981451106,337306001,10034339

In [4]:
# Загружаем с правильной строки, колонки 0,1,2 = номер, банк, активы
df_clean = pd.read_excel("../data/raw/nbk_2023_capital_assets.xls", header=None, skiprows=8)

# Оставим только нужные колонки
df_clean = df_clean[[0, 1, 2]].copy()

# Дадим понятные названия
df_clean.columns = ["number", "bank_name", "assets"]

# Уберём пустые строки
df_clean = df_clean.dropna(subset=["bank_name"])

df_clean.head(10)

   number                           bank_name        assets
0     1.0     "Halyk Bank of Kazakhstan", JSC  1.386279e+10
1     2.0                   "Kaspi Bank", JSC  5.086784e+09
2     3.0            "Bank CenterCredit", JSC  4.346623e+09
3     4.0                  "Otbasy bank", JSC  3.440105e+09
4     5.0                    "ForteBank", JSC  2.914127e+09
5     6.0  "First Heartland Jusan Bank", JSC   2.843662e+09
6     7.0                "Eurasian Bank", JSC  2.360046e+09
7     8.0               "Bank RBK" Bank", JSC  1.984418e+09
8     9.0                  "Bereke Bank", JSC  1.694923e+09
9    10.0         "Citibank Kazakhstan", JSC   1.334705e+09

In [5]:
import glob

all_files = {
    2023: "../data/raw/nbk_2023_capital_assets.xls",
    2024: "../data/raw/nbk_2024_capital_assets.xls",
    2025: "../data/raw/nbk_2025_capital_assets.xls",
    2026: "../data/raw/nbk_2026_capital_assets.xls",
}

frames = []

for year, path in all_files.items():
    df_temp = pd.read_excel(path, header=None, skiprows=8)
    df_temp = df_temp[[0, 1, 2]].copy()
    df_temp.columns = ["number", "bank_name", "assets"]
    df_temp = df_temp.dropna(subset=["bank_name"])
    df_temp["year"] = year
    frames.append(df_temp)

df_all = pd.concat(frames, ignore_index=True)
print(df_all.shape)
df_all.head(10)

(117, 4)

   number                           bank_name        assets  year
0     1.0     "Halyk Bank of Kazakhstan", JSC  1.386279e+10  2023
1     2.0                   "Kaspi Bank", JSC  5.086784e+09  2023
2     3.0            "Bank CenterCredit", JSC  4.346623e+09  2023
3     4.0                  "Otbasy bank", JSC  3.440105e+09  2023
4     5.0                    "ForteBank", JSC  2.914127e+09  2023
5     6.0  "First Heartland Jusan Bank", JSC   2.843662e+09  2023
6     7.0                "Eurasian Bank", JSC  2.360046e+09  2023
7     8.0               "Bank RBK" Bank", JSC  1.984418e+09  2023
8     9.0                  "Bereke Bank", JSC  1.694923e+09  2023
9    10.0         "Citibank Kazakhstan", JSC   1.334705e+09  2023

In [6]:
# Сохраняем в processed
df_all.to_csv("../data/processed/banks_financial_health_clean.csv", index=False)
print("Сохранено!")

Сохранено!

In [7]:
# Посмотрим ВСЕ строки файла 2023
df_raw = pd.read_excel("../data/raw/nbk_2023_capital_assets.xls", header=None)
print(f"Всего строк: {len(df_raw)}")
df_raw.iloc[:, 0:3]

Всего строк: 41

,0,1,2
0,NaN,NaN,NaN
1,Two tier banks' Financial indicators1 on Janua...,NaN,NaN
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,№,Name of two tier bank,Assets
5,NaN,NaN,NaN
6,NaN,NaN,NaN
7,NaN,NaN,NaN
8,1,"""Halyk Bank of Kazakhstan"", JSC",13862789955
9,2,"""Kaspi Bank"", JSC",5086784318
10,3,"""Bank CenterCredit"", JSC",4346622613
11,4,"""Otbasy bank"", JSC",3440104965
12,5,"""ForteBank"", JSC",2914126826
13,6,"""First Heartland Jusan Bank"", JSC",2843661507
14,7,"""Eurasian Bank"", JSC",2360045578
15,8,"""Bank RBK"" Bank"", JSC",1984418179
16,9,"""Bereke Bank"", JSC",1694922688
17,10,"""Citibank Kazakhstan"", JSC",1334705356
18,11,"""Bank Freedom Finance Kazakhstan"", JSC",1264198200
19,12,"""Altyn Bank"", JSC (SB of China Citic Bank Corp...",981451106
20,13,"""Home Credit Bank"", Joint Stock Company",551954564
21,14,"Subsidiary Bank ""Bank of China in Kazakhstan"",...",550684248
22,15,"""Nurbank"", JSC",468758948
23,16,"""Industrial and Commercial Bank of China in Al...",290361506
24,17,"Subsidiary JSC ""Bank VTB (Kazakhstan)""",192889251
25,18,"SB ""KAZAKHSTAN-ZIRAAT INTERNATIONAL BANK"", JSC",171056372
26,19,"""Shinhan Bank Kazakhstan"", JSC",126385913
27,20,"""Al-Hilal"" Islamic Bank"", JSC",60315857
28,21,"""Islamic bank ""Zaman-Bank"", JSC",36090236
29,NaN,Total:,44562328187
30,NaN,NaN,NaN
31,1,The information was prepared on the basis of u...,NaN
32,2,Loans include accounts for the group of accoun...,NaN
33,3,Loans for which there is overdue debt on the m...,NaN
34,4,The amount of overdue loans (including overdue...,NaN
35,NaN,NaN,NaN
36,NaN,NaN,NaN
37,NaN,,NaN
38,NaN,NaN,NaN
39,NaN,NaN,NaN
40,NaN,,NaN

In [8]:
frames = []

for year, path in all_files.items():
    df_temp = pd.read_excel(path, header=None, skiprows=8)
    df_temp = df_temp[[0, 1, 2]].copy()
    df_temp.columns = ["number", "bank_name", "assets"]
    
    # Убираем строки где number не является числом (Total, примечания)
    df_temp = df_temp[pd.to_numeric(df_temp["number"], errors="coerce").notna()]
    df_temp["year"] = year
    frames.append(df_temp)

df_all = pd.concat(frames, ignore_index=True)
print(df_all.shape)
df_all

(106, 4)

,number,bank_name,assets,year
0,1.0,"""Halyk Bank of Kazakhstan"", JSC",1.386279e+10,2023
1,2.0,"""Kaspi Bank"", JSC",5.086784e+09,2023
2,3.0,"""Bank CenterCredit"", JSC",4.346623e+09,2023
3,4.0,"""Otbasy bank"", JSC",3.440105e+09,2023
4,5.0,"""ForteBank"", JSC",2.914127e+09,2023
...,...,...,...,...
101,2.0,Loans include accounts for the group of accoun...,NaN,2026
102,3.0,Loans for which there is overdue debt on the m...,NaN,2026
103,4.0,Stage 3 includes loans for which events have b...,NaN,2026
104,5.0,The amount of overdue loans (including overdue...,NaN,2026
105,6.0,Provisions for the loan portfolio have been fo...,NaN,2026

In [9]:
frames = []

for year, path in all_files.items():
    df_temp = pd.read_excel(path, header=None, skiprows=8)
    df_temp = df_temp[[0, 1, 2]].copy()
    df_temp.columns = ["number", "bank_name", "assets"]
    
    # Убираем строки где number не число
    df_temp = df_temp[pd.to_numeric(df_temp["number"], errors="coerce").notna()]
    
    # Убираем строки где assets пустой
    df_temp = df_temp[df_temp["assets"].notna()]
    
    df_temp["year"] = year
    frames.append(df_temp)

df_all = pd.concat(frames, ignore_index=True)
print(df_all.shape)
df_all

(86, 4)

    number                                       bank_name        assets  year
0      1.0                 "Halyk Bank of Kazakhstan", JSC  1.386279e+10  2023
1      2.0                               "Kaspi Bank", JSC  5.086784e+09  2023
2      3.0                        "Bank CenterCredit", JSC  4.346623e+09  2023
3      4.0                              "Otbasy bank", JSC  3.440105e+09  2023
4      5.0                                "ForteBank", JSC  2.914127e+09  2023
..     ...                                             ...           ...   ...
81    19.0  SB "KAZAKHSTAN-ZIRAAT INTERNATIONAL BANK", JSC  3.070382e+08  2026
82    20.0         Subsidiary JSC "Bank VTB (Kazakhstan)"   2.669745e+08  2026
83    21.0                       "ADCB" Islamic Bank", JSC  2.561803e+08  2026
84    22.0                 "Islamic bank "Zaman-Bank", JSC  4.495690e+07  2026
85    23.0                       "BNK Commercial Bank" JSC  2.334020e+07  2026

[86 rows x 4 columns]

In [10]:
df_all.to_csv("../data/processed/banks_financial_health_clean.csv", index=False)
print("Сохранено!")

Сохранено!

In [11]:
# Посмотрим строку с заголовками (строка 4)
df_raw = pd.read_excel("../data/raw/nbk_2023_capital_assets.xls", header=None)
df_raw.iloc[4:8, :]

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
4,№,Name of two tier bank,Assets,Total loans2,NaN,"of these, loans with overdue payments3",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,in all,including,over 7 days,NaN,over 30 days,NaN,over 90 days,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,Reverse REPO operations,amount,share in loan portfolio,amount,share in loan portfolio,amount,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Выведем все колонки строки 4 по одной
for i, val in enumerate(df_raw.iloc[4]):
    print(f"Колонка {i}: {val}")

Колонка 0: №
Колонка 1: Name of two tier bank
Колонка 2: Assets
Колонка 3: Total loans2
Колонка 4: nan
Колонка 5: of these, loans with overdue payments3
Колонка 6: nan
Колонка 7: nan
Колонка 8: nan
Колонка 9: nan
Колонка 10: nan
Колонка 11: Overdue amount, including overdue interest4
Колонка 12: Provisions made for lending portfolio by ISFR
Колонка 13: Liabilities
Колонка 14: including deposits*
Колонка 15: nan
Колонка 16: Capital
Колонка 17:  Exceeding of current income (expenses) over current expenses (income)  after income tax
Колонка 18: nan
Колонка 19: nan
Колонка 20: nan
Колонка 21: nan
Колонка 22: nan
Колонка 23: nan
Колонка 24: nan
Колонка 25: nan
Колонка 26: nan
Колонка 27: nan

In [13]:
frames = []

for year, path in all_files.items():
    df_temp = pd.read_excel(path, header=None, skiprows=8)
    df_temp = df_temp[[0, 1, 2, 3, 13, 14, 16, 17]].copy()
    df_temp.columns = ["number", "bank_name", "assets", "loans", "liabilities", "deposits", "equity", "net_income"]
    
    df_temp = df_temp[pd.to_numeric(df_temp["number"], errors="coerce").notna()]
    df_temp = df_temp[df_temp["assets"].notna()]
    
    df_temp["year"] = year
    frames.append(df_temp)

df_all = pd.concat(frames, ignore_index=True)
print(df_all.shape)
df_all.head()

(86, 9)

,number,bank_name,assets,loans,liabilities,deposits,equity,net_income,year
0,1.0,"""Halyk Bank of Kazakhstan"", JSC",1.386279e+10,8.087488e+09,1.197611e+10,5.137146e+09,1.886682e+09,539280069.0,2023
1,2.0,"""Kaspi Bank"", JSC",5.086784e+09,3.380025e+09,4.542690e+09,3.699473e+09,5.440944e+08,361709053.0,2023
2,3.0,"""Bank CenterCredit"", JSC",4.346623e+09,2.161666e+09,4.072048e+09,1.888551e+09,2.745749e+08,145004425.0,2023
3,4.0,"""Otbasy bank"", JSC",3.440105e+09,2.984578e+09,2.977844e+09,2.187315e+09,4.622612e+08,96035130.0,2023
4,5.0,"""ForteBank"", JSC",2.914127e+09,1.275637e+09,2.586495e+09,7.761670e+08,3.276314e+08,92904022.0,2023

In [14]:
df_all.to_csv("../data/processed/banks_financial_health_clean.csv", index=False)
print("Сохранено!")

Сохранено!